name: Run tests

on:
  push:
    branches: [ "master" ]
 
jobs:
  run:
    name: Run tests
    uses: moosetechnology/.github/.github/workflows/run-tests.yml@main
    secrets: inherit
    with:
      create-artifact: true
      pharo-versions: '[ Moose64-trunk ]'
